### ISSUE TITLE
The App Is much slower than the original and can not replicate its behaviour

### ISSUE THREAD

**Issue by fieraoh** [rasoulia/PSXDownloader#1]
First of all I would like to express how grateful I am for the UI you have created for this application
however, there is something wrong with how the app process file transfers, I do not know if is because you have not implemented CDN acceleration within the app or not.

The file transfers start at regular speed but then de accelerates until it virtually stops.

Could you look into this?

**Comment by rasoulia** [comment]
Thanks for your feedback.
that problem is because the program have a unsolved problem that cause high cpu and ram usage. and because of that the speed is very low or is 0.
I am working on a fix for repair that problem. but can't find a way to fix that problem.

**Comment by fieraoh** [comment]
I have checked most of your code, and I assume it to be a valid rewrite of the original, But to be sure, have you tried to use the original code for the DLLs except for the "MVVM"?

also, I can't debug the program because I do not have Visual Studio Code on the PC I use for transferring files, I will try it out later and tell you.

**Comment by rasoulia** [comment]
tha main program have to part
1. Core: for socket programming and anything that related to transfer, connect, etc I use this part of old program without touching it.
2. Design: this is my part. I only design the program. that's all.
the old program work fine. but in my program is not work as  expected.

this part is the problem (https://github.com/rasoulia/PSXDownloader/blob/main/PSXDLL.HttpsHelp/HttpClient.cs):
`        private void OnLocalFileSent(IAsyncResult ar)
        {
            try
            {
                if (_mLocalFile!.FileStream!.Position < _mLocalFile.FileStream.Length)
                {
                    byte[] buffer = new byte[1024 * 4];
                    _mLocalFile.FileStream.Read(buffer, 0, buffer.Length);
                    ClientSocket?.BeginSend(buffer, 0, buffer.Length, SocketFlags.None, OnLocalFileSent, ClientSocket);
                }
                else
                {
                    ClientSocket?.EndSend(ar);
                    _mLocalFile.FileStream.Close();
                }
            }
            catch
            {
                _mLocalFile!.FileStream!.Close();
                Dispose();
            }
        }`

**Comment by rasoulia** [comment]
I finally fix it. wait for new build
