### ISSUE TITLE
The program does not run

### ISSUE THREAD

**Issue by boonuehjsne** [rasoulia/PSXDownloader#2]
Hello friend, the program does not run, I don't know the reason, but during the run time, I installed a special version of Microsoft Run Time that the program requires, and the program still did not run, I would be happy to know the reason.

**Comment by rasoulia** [comment]
hi. download the latest version of net 6 from microsoft website. and seee it's work or not.
then if not work. go to event viewer and find the log that related to this program. and send it here to find the reason of that problem

**Comment by drcayber** [comment]
Hi bro .
What about your program, when will you broadcast it?

**Comment by rasoulia** [comment]
hi.
when i am 100% sure that program has no bug. currently have slow start bug (it's took 10 minutes to start transfer data)

**Comment by drcayber** [comment]
> hi.
> when i am 100% sure that program has no bug. currently have slow start bug (it's took 10 minutes to start transfer data)

Ok bro
