### ISSUE TITLE
نمیتونم راه‌اندازی کنم

### ISSUE THREAD

**Issue by IRONB0SS** [rasoulia/PSXDownloader#3]
سلام داداش،‌ خسته نباشی
من با PSX dl helper 1.8 وقتی تو نوتیفکشن‌سنتر بازی resume میکنم لینک اضافه میشه اما با برنامه تو هیچی نمیاد بالا، resume که میکنم جایی نیست که بیام لینک رو بردارم

**Comment by rasoulia** [comment]
سلام. سلامت باشی.
در همون صفحه اصلی زیر قسمت آی پی و پورت یه بخشی هست که برای لاگ استفاده میشه اونجا میتونی لینک رو برداری.

**Comment by IRONB0SS** [comment]
سلام مجدد، برنامه تا لینک اوکیه، الان مشکل اینه دیتا رو از PC نیمیگیره

![image](https://github.com/rasoulia/PSXDownloader/assets/97769328/f42e4f2a-b78d-47d4-9107-ce7e0b9d2a2c)
این گزینه رو میزنم، Select Folder میزنم اما جلوی Local Path چیزی نمینویسه
بعد داداش اگه برات مقدوره رو گزینه ها mouse hover اضافه کن و توضیح مختصری در موردشون بده
.
یکی هم اینه وقتی به برنامه لینک اضافه میشه، خودکار پنجره لینک بازی جمع میشه
collapse mishe
![image](https://github.com/rasoulia/PSXDownloader/assets/97769328/449faa2e-9d13-43b7-af41-25a0704815fb)
اینو هم بتونی کارش بکنی عالی میشه

**Comment by rasoulia** [comment]
سلام. اون قسمت که شما رفتید. برای افزودن یه دونه بازیه برای افزودن تمام بازی ها علامت پلاس رو بزن که تمام بازی ها رو اضافه کنه.
اون مشکل هم فعلا وقت ندارم سر فرصت ختما درستش میکنم

**Comment by IRONB0SS** [comment]
بعد از زدن + در قسمت Database، مسیری به local path اضافه نمیشه
![image](https://github.com/rasoulia/PSXDownloader/assets/97769328/f8981994-6309-47a3-8ea4-72d637e6b402)

دیتای بازی رو انداختم مسیر زیر
C:\Users\SAFARI-PC\Downloads\New folder
بعد + رو میزنم Select Folder میزنم، بازی رو Resume میکنم از نت میره
![image](https://github.com/rasoulia/PSXDownloader/assets/97769328/3b7cc85d-74a7-46a4-8816-d1dd5ab04a50)

با PSX اورجینال راحت دیتا میره

**Comment by rasoulia** [comment]
یه سوتی که من دادم اینه که بازی های چند پارت رو خودش اضافه میکنه بازی های تک پارت مثل برای شما باید دستی اضافه بشه. شما اول مسیر پوشه رو به قسمت localpath کپی کن سپس سایر قسمت ها رو تکمیل که فقط مطمئن شو که کد CUSA بازی رو با حروف بزرگ و درست وارد کنی. 
حتما سر فرصت این سوتی رو درستش میکنم. اولویت اصلی من ظاهر برنامه است که بتونم چیزی که میخوام رو درست کنم.

**Comment by rasoulia** [comment]
نسخه جدید برنامه با اسم PSXTransfer منتشر شد. هیچ کدوم از این مشکلات رو هم نداره

**Comment by IRONB0SS** [comment]
سلام تو موقعیت مناسب تست میکنم و فیدبک میدم
تشکر بابت زحماتت 🙌

**Comment by rasoulia** [comment]
سلام خواهشمندم

**Comment by IRONB0SS** [comment]
@rasoulia 
داداش برنامه رو تست کردم، اصلا راهی پیدا نکردم که محل فایل بازیا رو به برنامه بدم

![image](https://github.com/rasoulia/PSXDownloader/assets/97769328/020397a2-e9de-43e1-a132-1ae267da0cbe)

**Comment by rasoulia** [comment]
دو تا آیکون زیر قسمت آی پی هست دکمه سمت چپی اون رو بزنید.

**Comment by IRONB0SS** [comment]
بازم نمیذاره محل مشخص بشه، مستقیم این پیام میاد

![image](https://github.com/rasoulia/PSXDownloader/assets/97769328/451673b0-1d43-4744-b940-d3e1a2e3e31c)

اینم بگم بعد از زدن گزینه دیتابیس، برنامه یه مکث 10ثانیه ای هم میکنه

**Comment by rasoulia** [comment]
در نسخه جدید دیگه نمیخواد مسیر مشخص کنید خودش میاد کل هارد رو اسکن میکنه و هر چی فایل هست رو به دیتابیس اضافه میکنه.
الان کارش تمومه فقط تست کنید و دیتا انتقال بدید

**Comment by IRONB0SS** [comment]
آقا دمت گرم، حله
یه پیشنهاد هم داشتم، یه گزینه بذاری و اجازه بدی تم و رنگ برنامه رو کاربر تنظیم کنه من شخصا midnight blue رو بیشتر ترجیح میدم به این رنگ فعلی
تب About رو هم منتقل کنی به ستون Log و یه گزینه جدید اضافه کنی با آیکونی مثلا ?  و دست اندرکاران رو اونجا نمایش بدی
تو hover mouse آیکون دیتابیس هم اضافه کن که کاربر بدونه دیگه لازم نیست محل فولدر بازیا رو مشخص کنه

**Comment by rasoulia** [comment]
خواهش میکنم.
ممنون بابت پیشنهاداتتون فعلا سرم شلوغه ولی سر فرصت حتما درستش میکنم

**Comment by rasoulia** [comment]
سلام شروع کردم برنامه رو از دوباره طراحی می‌کنم. خواستم بدونم رنگ پس‌زمینه آبی باشه کافیه؟ کلا رنگ بندی مدنظرتون رو بگید تا به برنامه اعمال کنم.
