### ISSUE TITLE
Running app on MacOS

### ISSUE THREAD

**Issue by mortezaghafoori** [rasoulia/PSXDownloader#4]
Hi, can you please provide a guide on how to run and use the app on macOS?

**Comment by rasoulia** [comment]
Hi.
Sorry i don't have any macos and don't know how to run app on that os. So just google it.

**Comment by rasoulia** [comment]
But If you mean don't know how to use it's simple.
1. Downloader every game with latest update
2. Place all game PKG's and update PKG's in same folder.
3. Run program click on icon under IP Element. Wait up to 1 minute for program that add every single pkg to database.
4. Connect  ps4/ps5 to the same network that your PC/laptop connect it.
5. In console config use custom and in proxy use manually and then add ip address and port that is exit in program.
5. Done download your games and program automatically transfer it from pc to your console

**Comment by mortezaghafoori** [comment]
No, I know how to use it. It's just that I don't know what to do to get the app running on macOS, the  MAC folder only contains a .dylib file and a document file (at least that's what my mac recognizes). Do I have to compile it somehow?

**Comment by rasoulia** [comment]
No it's executable file. You don't have to do anything. Just download .Net 6 runtime for macos from microsoft site. After that maybe you can run it. And one thing download psxtransfer it's better and simpler than this
Maybe this document help you

https://learn.microsoft.com/en-us/dotnet/core/install/macos

Update: After installing net 6 runtime go to psxtranfer folder run command line program and then write this
`dotnet psxtransfer.dll`
I hope this work for run program

**Comment by mortezaghafoori** [comment]
That didn't work either. maybe it is because my macbook has apple silicon m2 chip and it's not currently supported?

**Comment by rasoulia** [comment]
https://m.youtube.com/watch?v=Jr0XGKHoYU0

**Comment by mortezaghafoori** [comment]
I know how to install it, I've already downloaded the runtime shown in video, but the thing is I can't run the app.
When I download PSXTransfer from the link, I get a file named PSXTransfer.02.exe and when I open it, it unzips to a folder named PSXTransfer.02 which has 4 folders inside it (Linux, Mac, Windows X64, and Windows x86). Can you tell me exactly what to run and how? Because I tried the dotnet command line in all folders and none worked.
Sorry if this is taking your time but this is really my first time running a windows app on macos

**Comment by rasoulia** [comment]
Sorry for delay.
np but i have zero experience at macos and don't know how. Maybe this help you.
https://www.howtogeek.com/187359/5-ways-to-run-windows-software-on-a-mac/

You only need mac folder

**Comment by mortezaghafoori** [comment]
I've been using windows 11 ARM for quite sometime and I was hoping to find an app to run directly on macOS. I have no problems with windows 11 ARM and thank you so much for your time. Maybe oneday I'll learn to compile something similar for macOS.

**Comment by rasoulia** [comment]
You're welcome.
Sorry that's all i can help you. If i find a way to run mac on windows with vmware or virtualbox. Maybe i find a way that how to run app on mac.
And because of dot net that is multi platform. I created some thing like this.

**Comment by rasoulia** [comment]
https://www.michaelcrump.net/part3-aspnetcore/

https://swaminathanvetri.in/2016/06/21/running-your-first-net-core-app-in-mac/
