### ISSUE TITLE
برنامه Gamepad Tester

### ISSUE THREAD

**Issue by IRONB0SS** [rasoulia/PSXDownloader#5]
سلام داداش، خسته نباشی 
بابت اسپم معذرت، اما چون تلگرامت رو نداشتم اجبارا issue میزنم

میتونی وبسایت پایینی رو به برنامه تبدیل ویندوز تبدیل کنی که آفلاین کار کنه؟

https://hardwaretester.com/gamepad

the gamepad tester section would be enough, also with dark mode and let users choose controller between Xbox and PS

I don't have much knowledge about coding but they added this message to their website : "Are you a developer interested in using the Gamepad API? Check out this [quick guide.](https://hardwaretester.com/gamepad/for-developers)"

پیشاپیش تشکر ❤️ اگه رایگان نمیشه، هزینش چند میشه؟

**Comment by rasoulia** [comment]
سلام. سلامت باشی.
خود سایت متاسفانه پیجی در گیتهاب نداره که بشه دستکاریش کرد ولی داخل صفحه اصلی سایت میرم ببینم میشه به تمام کدهاش دسترسی پیدا کرد یا نه.
ولی در کل این قابلیت به صورت وبی خوبه چون به راحتی میشه چیزی که میبینید رو نمایش داد.
در مورد هزینه هم رایگان انجام میدم چون تجربه‌ام کمه چالش خوبی میشه که بتونم به هم چنین کاری انجام بدم. قول ۱۰۰ درصد نمیدم ولی سر فرصت حتما به نگاهی میندازم که ببینم چی کار میتونم بکنم.

**Comment by rasoulia** [comment]
سلام. رفتم یه بررسی کوچیکی انجام دادم. از خود سایت اصلی چیزی سر در نیاوردم. در مورد انجام اون با سی شارپ هم متاسفانه چیزی پیدا نکردم. اگه خودتون سر رشته ای از برنامه نویسی دارید و چیزی پیدا کردید. اینجا ارسال کنید بررسی میکنم که ببینم میتونم کاری انجام بدم یا نه. هم چنین مورد زیر رو بررسی کنید ببینید کارتون رو راه میندازه یا نه.
https://github.com/davidcmoffitt/gamepad-controller-test
 

همچنین نسخه دمو برنامه زیر هم ممکنه همون چیزی باشه که میخواین.
https://github.com/AderitoSilva/XInputium

**Comment by IRONB0SS** [comment]
سلام؛ بابت وقت و زمانی که گذاشتی ممنونم
متاسفانه هیچ سررشته ای از برنامه نویسی ندارم
و اما اون 2 لینکی هم که فرستادی تست کردم هیچکدوم دسته PS4 رو نشناخت

**Comment by IRONB0SS** [comment]
اینو پیدا کردم و کار میکنه
https://github.com/luser/gamepadtest

همینو میتونی بهترش کنی؟ خوبیش اینه میشه با باز کردن فایل index بصورت آفلاین باهاش کار کرد

**Comment by rasoulia** [comment]
خواهشمندم. از چه نظر بهتر بشه؟ دقیقا دوست دارید به چه صورت باشه؟

**Comment by IRONB0SS** [comment]
داداش ببخشید که سرتو درد آوردم، یکی پیدا کردم دقیقا خود جنسه
https://github.com/greggman/html5-gamepad-test

**Comment by rasoulia** [comment]
خواهشمندم. خوشحالم که مشکلتون حل شده.

**Comment by IRONB0SS** [comment]
> خواهشمندم. خوشحالم که مشکلتون حل شده.

ممنونم، راستی این فیدبک رو در نظر دارید اوکیش کنید؟
https://github.com/rasoulia/PSXDownloader/issues/3#issuecomment-1741706211

**Comment by rasoulia** [comment]
بله صد در صد. مشغول یه پروژه‌ای بودم آخرای اونم. حتما انجام میدم.

**Comment by IRONB0SS** [comment]
> بله صد در صد. مشغول یه پروژه‌ای بودم آخرای اونم. حتما انجام میدم.

یه دونه‌اید، موفق باشید داداش

**Comment by rasoulia** [comment]
سلامت باشی.
