### ISSUE TITLE
Redesign Feedback

### ISSUE THREAD

**Issue by IRONB0SS** [rasoulia/PSXDownloader#6]
سلام شروع کردم برنامه رو از دوباره طراحی می‌کنم. خواستم بدونم رنگ پس‌زمینه آبی باشه کافیه؟ کلا رنگ بندی مدنظرتون رو بگید تا به برنامه اعمال کنم.

_Originally posted by @rasoulia in https://github.com/rasoulia/PSXDownloader/issues/3#issuecomment-1848371429_

سلام داداش، خوبی
کامنت رو قفل کرده بودی اجبارا issue جدید زدم

Background : #0d1117
font color : #e6edf3
Buttons background : #21262d
Button font color : #c9d1d9

**Comment by rasoulia** [comment]
عالی. فقط یه رنگ فرستادی. بقیه قسمت‌ها هم بفرستید راستی بزو psxhax نسخه جدید با تم تاریح و زوشن فرستادم اونجا دانلود کن. و مطابق اون طراحی رنگبندیت رو ارسال کن قسمت های مختلفی رنگ بندی بهشون اضافه شده. اگه اطلاع ندارید اسم نسخه جدید psxtransfer شده. از اونجایی که در این قسمت ارسال کردید میگم که شاید در جریان نباشید

**Comment by IRONB0SS** [comment]
> عالی. فقط یه رنگ فرستادی. بقیه قسمت‌ها هم بفرستید راستی بزو psxhax نسخه جدید با تم تاریح و زوشن فرستادم اونجا دانلود کن. و مطابق اون طراحی رنگبندیت رو ارسال کن قسمت های مختلفی رنگ بندی بهشون اضافه شده.

تشکر، ویرایش زدم، داشتم دونه دونه اضافه میکردم

**Comment by IRONB0SS** [comment]
![Screenshot 2023-12-10 233957 copy](https://github.com/rasoulia/PSXDownloader/assets/97769328/3e5c6e82-7190-4584-a8cd-77e1a54efc43)

Font : Open Sans
Background : #0d1117
font color : #e6edf3
Buttons background : #21262d
Button font color : #c9d1d9
نوار :
#c9dae5
checkbox : #c9dae5
جریان اون offline Transfer? و is connected? یادم رفته، چی بودن؟

![image](https://github.com/rasoulia/PSXDownloader/assets/97769328/c3273366-19ca-48e4-a243-0046382e5630)

نظرت؟

حتی میشه پشت دکمه ها با بکگراند یکی بشه
![Screenshot 2023-12-10 233957 copy](https://github.com/rasoulia/PSXDownloader/assets/97769328/93004405-cc05-42dc-950c-6d37576d5122)

بنظرم همه دکمه ها رو بردار ببر به ستون settings و Tutorial هم آخر ستینگز باشه و ستون Log خالی باشه

بعد داداش اندازه پنجره برنامه رو نمیشه دلبخواه کرد

بتونی هم به برنامه exclude folder اضافه کنی عالی میشه، فایلهایی که نمیخوام به دیتابیس اضافه بشه رو دیگه اضافه نکنه، من حدودا 12ترا دیتای با فرمت Pkg دارم و برا همین خیلی طول میکشه دیتابیس آپدیت بشه

صفحه گیت هابتو هم خواستی به برنامه اضافه کن

![Screenshot 2023-12-10 233957 copy 2](https://github.com/rasoulia/PSXDownloader/assets/97769328/e3eca6f1-b564-4209-adff-6c580b9d6fe6)

link color : #0173ac چک کن ببین قشنگ میشه یا نه
سایز فونت لینک رو هم یک یا دو عدد ریزتر از بقیه جاها بشه

اینا رو هم خواستی بچسبون و با hover مشخص کن که قابل کلیکه
![image](https://github.com/rasoulia/PSXDownloader/assets/97769328/0e6224e4-153a-4bf7-9ae3-770da0c74102)

**Comment by rasoulia** [comment]
Offline transfer برای زمانیه که بخواهید اطلاعات از سمت سیستم به دستکاه منتقل بشه. گزینه مشابه این در تنظیمات نسخه اصلی هست فکر کنم اسمش Autofind

Is connected هم بعنی اتصال برنامه بازه و دستکاه میتونه بهش وصل بشه
رنگ بندی که فرستادی خوبه اگه میتونی برای حالت روشن هم یه هم چنین رنگ بندی درست کن.
اره این طوری بهتره اگه بتونم انجامش مبدم و همه قسمت های لاگ رو به هم وصل میکنم.
متوجه بخش جابه جایی دکمه ها نشدم. یعنی بخش لاگ جدا باشه بخش دکمه ها و تنظیات جدا باشه؟ یعنی دو تا تب Log و Setting باشه؟
خود برنامه اونایی که داخل دیتابیس هست رو رد میکنه. مشکل طول کشیدن هم فکر کنم یه ایرادی داره که زیاد طول میکشه. بررسی میکنم ببینم میتونم پیداش کنم یا نه.
اندازه قابل تغییر هم ببینم میتونم بهش اضافه کنم یا نه.
صفحه گیتهاب برنامه جدید هم هست.

**Comment by rasoulia** [comment]
چند تا نکته.
۱. زمانی که رنگ رو روی پروژه اعمال کردم بیش از حد تاریک شد. به نظرم رنگ تم تاریک من بهتر باشه.
۲. نکاتی که برای طراحی گفتید از طراحی من بهتره و سعی میکنم اعمالشون کنم.
۳. رنگ بندی رو لطفا مطابق ترتیب ارسال کنید رنگ بندی کل صفحه برنامه، بالای صفحه برنامه، رنگ بندی بخش تنظیمات و رنگ‌بندی بخش لاگ برنامه.
۴. اگه باز هم اون تم مورد علاقه شماست بگید که با همون رنگ مد نظر شما تم رو روی برنامه اعمال کنم. فقط لطف کنید مطابق شرایط گزینه ۳ ارسال کنید

**Comment by IRONB0SS** [comment]
نظرت راجع به این طراحی چیه؟

![Untitled-1](https://github.com/rasoulia/PSXDownloader/assets/97769328/427f8c56-df66-4315-8f43-bd3833848b83)

با اون جارو "clear log" صورت میگیره، میتونی ببری سمت چپ تا اسکرولر به سمت راست اضافه کنی

راهنما، About Us و حتی انتخاب تم هم به (i)، اون بالا بغل minimize منتقل شده

بنظرم is connected? و is offline? رو هم جایگزین Auto find و Start Server بکنی بهتره

سرور استاتوس هم با Connected و Disconnected نمایش داده بشه، اگه تنظیمات کنسول و PC درست باشه Connected رو نشون بده، در غیر اینصورت Disconnected با رنگ قرمز

وقتی هم لاگی وجود نداشته باشی، اون وسط یه دونه بنویسی No log

یه پیشنهاد اختیاری : وقتی رو دیتابیس کلیک بشه، داخل button خود دیتابیس یه رنگ مثلا سفید با capacity 25% از سمت چپ button شروع بشه، منظور اینه خود دکمه به عنوان progress bar استفاده بشه بعد که آپدیت دیتابیس تموم شد برگرده به رنگ قبلی خودش

![ezgif com-video-to-gif (1)](https://github.com/rasoulia/PSXDownloader/assets/97769328/187e331c-0514-477a-91c0-4573b7df8668)

اگه اوکی رو بدی رنگ‌بندی ها رو بفرستم، درضمن ۳تا مود بذاریم بهتره، یکی لایت، یکی Darkی که الان هم هست یکی هم Midnight Blue که اینه

**Comment by rasoulia** [comment]
طراحی فوق العاده خوبیه. خوشم اومد. سعی میکنم یه هم چنین چیزی بسازم.
در مورد دکمه دیتابیس هم اول باید بتونم کاری کنم که نرم افزار هنگ نکنه بعد اون حالت رو اجرا کنم.

**Comment by rasoulia** [comment]
تقریبا کار برنامه تمومه. در مورد تب ها هر چه قدر سعی کردم نتونستم چیزی بسازم که بتونم اون رو حذف کنم و جای اون رو عوض کنم. به خاطر همین فعلا همین طوری مونده. در مورد بخش تنظیمات و لاگ یه چیز مشابه طرح شما ساختم. فقط میمونه رنگ‌بندی برنامه که مطابق ترتیبی که بهتون گفتم برام ارسال کنید تا تم مد نظر شما هم اعمال بشه.

**Comment by IRONB0SS** [comment]
> تقریبا کار برنامه تمومه. در مورد تب ها هر چه قدر سعی کردم نتونستم چیزی بسازم که بتونم اون رو حذف کنم و جای اون رو عوض کنم. به خاطر همین فعلا همین طوری مونده. در مورد بخش تنظیمات و لاگ یه چیز مشابه طرح شما ساختم. فقط میمونه رنگ‌بندی برنامه که مطابق ترتیبی که بهتون گفتم برام ارسال کنید تا تم مد نظر شما هم اعمال بشه.

تشکر بابت وقت و حوصلت
ممکنه یه اسکرین شات بفرستید؟

>رنگ بندی کل صفحه برنامه، بالای صفحه برنامه، رنگ بندی بخش تنظیمات و رنگ‌بندی بخش لاگ برنامه.

پس زمینه کلی
0d1117

نوار آبی رنگ
1e4273

پس زمینه بالای برنامه
010409

پس زمینه دکمه ها
252d36

رنگ فونت دکمه ها
c9d1d9

پس زمینه لاگ
21262d

رنگ فونت لینک های داخل لاگ
c9d1d9

پس زمینه تنظیمات
090e12

رنگ فونت توضیحات تنظیمات
a6c8cf or cbdae6

رنگ پس زمینه checkbox
5f8baf

تیک checkbox
ffffff

وضعیت connected
037b02

وضعیت disconnected
851a13

آیکون ها
c9d1d9

فونت برنامه
Open Sans Semibold

فونت لینک ها
Open sans Regular

**Comment by rasoulia** [comment]
فردا ارسال میکنم.
منظورتون از نوار آبی رنگ دقیقا کدوم قسمته؟ اسم تم Midnight بشه خوبه؟

**Comment by rasoulia** [comment]
نسخه جدید منتشر شد. برید دانلود کنید. امیدوارم همونی باشه که میخواین

**Comment by IRONB0SS** [comment]
سلام خسته نباشید داداش، بابت طراحی جدید و زمانی که گذاشتی ممنونم

![image](https://github.com/rasoulia/PSXDownloader/assets/97769328/b024ab38-b9b9-4487-a427-6c35e9636d43)

با طرحی که ارسال کرده بودم فاصله داره اما اینم اوکیه، تنها ایرادی که میتونم بگیرم رنگ 4 دکمه های چپی میبایست با دکمه database همرنگ میشد

پس زمینه دکمه ها
252d36
لینک هم کامل نمایش داده نمیشه
همچنین بازم درخواست میکنم که اگه ممکنه اجازه بدی درایو و فولدرهایی که موقع آپدیت دیتابیس نمیخوایم اسکن بشن رو به برنامه اضافه کنی

 بعد ممکنه سورس کد برنامه با آخرین تغییرات رو بفرستید؟ یا گیتهابتونو با کدهاش آپدیت کنید؟ میخوام بفرستم به یکی (ایرانی نیست) و UI رو به چیزی که فرستادم شبیه کنه یا اگه دلت نمی‌خواد صبر میکنم خودت اوکیش میکنی اصلا عجله‌ای ندارم

**Comment by rasoulia** [comment]
سلام سلامت باشی. لینک ها رو ایرادش مبدونم چیه. بعدا درستش میکنم. دیگه الان نباید سرعت کم باشه چون اون مشکل رو برطرف کردم.
فعلا همین طوری استفاده کنید بعدا این پروژه رو میخوام از صفر شروع کنم طراحی کنم به این زودی ها وقت نمیکنم.
سورس هم از همونی که تو صفحه است استفاده کنید طراحی طرف که تموم شد برای منم بفرستید تا روی پروژه اعمال کنم.
تا یه ساعت دیگه هم این دو تا مشکل کوچیک هم حلش میکنم برید نسخه ۰دیدش رو دانلود کنید

**Comment by IRONB0SS** [comment]
> سورس هم از همونی که تو صفحه است استفاده کنین

آخه من الان چک کردم سورس‌ها برا ۹ماه پیش هستن، اگه ممکنه سورس های آخرین تغییرات رو بفرستید

**Comment by rasoulia** [comment]
بنا به دلایلی کلا نمیخوام سورس جدید رو اشتراک بزارم. برنامه رو جورایی پولی میخواد بشه به خاطر همین نمی‌خوام سورس اون رو جایی قرار بدم.

**Comment by IRONB0SS** [comment]
موفق باشید پس ✌

استفاده من  از این برنامه کاملا صفره چون کنسولم کپیخوره و این فیدبکهایی که فرستادم فقط در راستای بهتر شدن برنامه بوده، به هر حال موفق باشی

**Comment by rasoulia** [comment]
سلامت باشی شما هم همین طور.
